// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: dataobj.proto

package datastore_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePath string `protobuf:"bytes,1,opt,name=FilePath,proto3" json:"FilePath,omitempty"`
	Offset   uint64 `protobuf:"varint,2,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Size     uint64 `protobuf:"varint,3,opt,name=Size,proto3" json:"Size,omitempty"`
}

func (x *DataObj) Reset() {
	*x = DataObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataobj_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataObj) ProtoMessage() {}

func (x *DataObj) ProtoReflect() protoreflect.Message {
	mi := &file_dataobj_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataObj.ProtoReflect.Descriptor instead.
func (*DataObj) Descriptor() ([]byte, []int) {
	return file_dataobj_proto_rawDescGZIP(), []int{0}
}

func (x *DataObj) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *DataObj) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DataObj) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type FileBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePath string `protobuf:"bytes,1,opt,name=FilePath,proto3" json:"FilePath,omitempty"`
	Offset   uint64 `protobuf:"varint,2,opt,name=Offset,proto3" json:"Offset,omitempty"`
}

func (x *FileBlock) Reset() {
	*x = FileBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataobj_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileBlock) ProtoMessage() {}

func (x *FileBlock) ProtoReflect() protoreflect.Message {
	mi := &file_dataobj_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileBlock.ProtoReflect.Descriptor instead.
func (*FileBlock) Descriptor() ([]byte, []int) {
	return file_dataobj_proto_rawDescGZIP(), []int{1}
}

func (x *FileBlock) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *FileBlock) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ExtendDataObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blocks []*FileBlock `protobuf:"bytes,1,rep,name=Blocks,proto3" json:"Blocks,omitempty"`
	Size   uint64       `protobuf:"varint,2,opt,name=Size,proto3" json:"Size,omitempty"`
}

func (x *ExtendDataObj) Reset() {
	*x = ExtendDataObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataobj_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtendDataObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendDataObj) ProtoMessage() {}

func (x *ExtendDataObj) ProtoReflect() protoreflect.Message {
	mi := &file_dataobj_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendDataObj.ProtoReflect.Descriptor instead.
func (*ExtendDataObj) Descriptor() ([]byte, []int) {
	return file_dataobj_proto_rawDescGZIP(), []int{2}
}

func (x *ExtendDataObj) GetBlocks() []*FileBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *ExtendDataObj) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_dataobj_proto protoreflect.FileDescriptor

var file_dataobj_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x64, 0x61, 0x74, 0x61, 0x6f, 0x62, 0x6a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0c, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x62, 0x22, 0x51, 0x0a,
	0x07, 0x44, 0x61, 0x74, 0x61, 0x4f, 0x62, 0x6a, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65,
	0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65,
	0x50, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65,
	0x22, 0x3f, 0x0a, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1a, 0x0a,
	0x08, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x22, 0x54, 0x0a, 0x0d, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x4f,
	0x62, 0x6a, 0x12, 0x2f, 0x0a, 0x06, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70,
	0x62, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x06, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dataobj_proto_rawDescOnce sync.Once
	file_dataobj_proto_rawDescData = file_dataobj_proto_rawDesc
)

func file_dataobj_proto_rawDescGZIP() []byte {
	file_dataobj_proto_rawDescOnce.Do(func() {
		file_dataobj_proto_rawDescData = protoimpl.X.CompressGZIP(file_dataobj_proto_rawDescData)
	})
	return file_dataobj_proto_rawDescData
}

var file_dataobj_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dataobj_proto_goTypes = []interface{}{
	(*DataObj)(nil),       // 0: datastore.pb.DataObj
	(*FileBlock)(nil),     // 1: datastore.pb.FileBlock
	(*ExtendDataObj)(nil), // 2: datastore.pb.ExtendDataObj
}
var file_dataobj_proto_depIdxs = []int32{
	1, // 0: datastore.pb.ExtendDataObj.Blocks:type_name -> datastore.pb.FileBlock
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dataobj_proto_init() }
func file_dataobj_proto_init() {
	if File_dataobj_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dataobj_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataobj_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataobj_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtendDataObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dataobj_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dataobj_proto_goTypes,
		DependencyIndexes: file_dataobj_proto_depIdxs,
		MessageInfos:      file_dataobj_proto_msgTypes,
	}.Build()
	File_dataobj_proto = out.File
	file_dataobj_proto_rawDesc = nil
	file_dataobj_proto_goTypes = nil
	file_dataobj_proto_depIdxs = nil
}
